max_steps_per_episode: 40
init_mol: C
fingerprint_radius: 2
fingerprint_length: 1024
discount_factor: 0.9
num_episodes: 200000
replay_buffer_size: 500
batch_size: 32
gamma: 1.0
update_frequency: 3
num_bootstrap_heads: 6
prioritized_alpha: 0.6
prioritized_beta: 0.4
prioritized_epsilon: 0.000001
save_frequency: 200
max_num_checkpoints: 10
distribution: False
noisy: True
n_layers: 1
n_neurons: 512
activation: ReLU
optimizer: Adam
dropout: 0
learning_frequency: 4
learning_rate: 0.0001
learning_rate_decay_steps: 10000
learning_rate_decay_rate: 0.9
adam_beta_1: 0.9
adam_beta_2: 0.999
grad_clipping: 10